### ISSUE TITLE
Ability to mark a BIE as deprecated

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1575]
There various instances where the ability to mark a profiled bie as deprecated would be beneficial.  Examples include when a earlier version of OAGIs is no longer supported and those profiled objects are now obsolete at a company.  When users make a small mistake like not enabling a typecode for an attribute, but do not want the schema without the typecode enabled used, etc.  This feature could mimic how Code Lists can be deprecated or have some of way make it visible in the view menu that the item is deprecated or this could be an additional state that happens after production.

**Comment by hakjuoh** [comment]
@smorgan19 Thanks for posting this issue. We have added a new feature for marking "Deprecated" to each BIE in the BIE edit view in versions 3.2.1 to address issue #1298. Here's an example screenshot that marks "Type Code" BIE as "Deprecated".

<img width="1003" alt="Screenshot 2023-11-14 at 11 15 58 AM" src="https://github.com/OAGi/Score/assets/16102116/c6280a3f-3e9b-4b7f-b6e8-e81b365c2065">

But, deprecated BIEs are expressed only in OpenAPI expressions with an added `deprecated` property as below.

```yml
  schemas:
    itemMaster:
      x-oagis-bie-guid: "f2a00253e74d47099a3006ddb3baeacb"
      x-oagis-bie-date-time: "2023-11-14T11:15:40-0500"
      x-oagis-bie-version: ""
      type: "object"
      additionalProperties: false
      properties:
        typeCode:
          example: ""
          type: "string"
          format: "token"
          deprecated: true
```

There are still outstanding questions about how to express these `deprecated` property marks in other expressions.
