### ISSUE TITLE
Pattern regex is not generating the way it used to 

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1633]
Something changed, and the Pattern regex is not coming in-line as it use to.

Currently, OpenAPI representation:

```
        telephoneNumber:
          description: "Primary telephone number for the send to party."
          type: "object"
          required:
          - "content"
          additionalProperties: false
          properties:
            content:
              allOf:
              - $ref: "#/components/schemas/type_d87c21021aa047889b2af79495c31deb"
              - example: "404.456.7890"
            typeCode:
              description: "Mobile | Home | Work"
              example: "Mobile"
              type: "string"
              format: "token"
```
The ref creates an allOf, and an additional C# class in Swagger CodeGen:
```
    type_d87c21021aa047889b2af79495c31deb:
      type: "string"
      pattern: "^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}$"
```

Historically, and correct representation:

```
        telephoneNumber:
          type: "object"
          required:
          - "content"
          additionalProperties: false
          properties:
            content:
              description: "Primary telephone number for the send to party."
              example: "404.456.7890"
              type: "string"
              pattern: "^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}$"
            typeCode:
              description: "Mobile | Home | Work"
              example: "Mobile"
              type: "string"
              format: "token"
```
This suppresses the allOf and the extra class.

Attachments.

[createissueongithubforpatternregex.zip](https://github.com/user-attachments/files/16629874/createissueongithubforpatternregex.zip)

**Comment by hakjuoh** [comment]
@dubnemo This issue might relate to the issue https://github.com/OAGi/Score/issues/1104
@kbserm

**Comment by hakjuoh** [comment]
@dubnemo @kbserm

Correct me if I'm wrong. What I remember (from Issue #753) is:
- allOf was added because an error occurred when an object containing a `$ref` property also had other properties.
- oneOf was added to support `nillable` properties.

But, to generate the schema like in the example, we would need to remove `$ref`.
I applied this rule: 

> If the 'type' is a primitive type defined by JSON Schema, do not generate '$ref'.

This way, the expressions will come out as intended, like the examples below (I couldn't find "Telephone Number" in connectSpec, so used "Building Number" instead). 

```yml
buildingNumber:
  type: "object"
  required:
  - "content"
  additionalProperties: false
  properties:
    content:
      type: "string"
      pattern: "^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}$"
      description: "Primary telephone number for the send to party."
      example: "404.456.7890"
    typeCode:
      description: "Mobile | Home | Work"
      example: "Mobile"
      type: "string"
      format: "token"
```
